# -*- coding: utf-8 -*-
"""Teri-U2rUs-Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ydWhZLaem7HLVY7_nCm3TVvu6P_sVZkt
"""

import spacy
import re
import nltk
nltk.download('punkt')

from time import sleep
import sys


# Load the spaCy NLP model
nlp = spacy.load("en_core_web_sm")

# Questions that are asked to connect users with recommendations

def ask_question(qn):
    print
    resp = input(qn)
    if resp.lower() in ["yes", "y", "yea", "^r'y"]:
        return True
    else:
        return False

responses = {(True, True, True) : "\nTeri: Based on your answers, here are a few resources that may be helpful: \n\nFibroids are tumors made of smooth muscle cells and fibrous connective tissue that develop in the uterus. It is estimated that 70 to 80 percent of women will develop fibroids in their lifetime — however, not everyone will develop symptoms or require treatment. Read more from UCLA Health - https://www.uclahealth.org/medical-services/fibroids/what-are-fibroids\n\nHysterectomy rates among Black women are more than double those of any other ethnic group.This statistic is rooted in the fact that some Black women are only offered this option. Read more on the experiences of Black women living fibroids at VeryWellHealth.com - https://www.verywellhealth.com/uterine-fibroids-coping-5188641\n\nUterine fibroids often aren't dangerous. But they can cause pain, and they may lead to complications. These include a drop in red blood cells called anemia. That condition can cause fatigue from heavy blood loss. Read more on the symptoms and causes of fibroids from the Mayo Clinic - https://www.mayoclinic.org/diseases-conditions/uterine-fibroids/symptoms-causes/syc-20354288#:~:text=Uterine%20fibroids%20often%20aren%27t,fatigue%20from%20heavy%20blood%20loss \n\nMost women will experience no effects from fibroids during their pregnancy. However, a 2010 review suggests 10 to 30 percent  of women with fibroids develop complications during pregnancy. Read more on how fibroids affect pregnancy and fertility?- https://www.healthline.com/health/womens-health/fibroids-pregnancy \n\nTeri: Thank you for the chat today. Come back anytime you have more questions.\n",
             (True, True, False) : "\nTeri: Based on your answers, here are a few resources that may be helpful: \n\nFibroids are tumors made of smooth muscle cells and fibrous connective tissue that develop in the uterus. It is estimated that 70 to 80 percent of women will develop fibroids in their lifetime — however, not everyone will develop symptoms or require treatment. Read more from UCLA Health - https://www.uclahealth.org/medical-services/fibroids/what-are-fibroids\n\nHysterectomy rates among Black women are more than double those of any other ethnic group.This statistic is rooted in the fact that some Black women are only offered this option. Read more on the experiences of Black women living fibroids at VeryWellHealth.com - https://www.verywellhealth.com/uterine-fibroids-coping-5188641\n\nUterine fibroids often aren't dangerous. But they can cause pain, and they may lead to complications. These include a drop in red blood cells called anemia. That condition can cause fatigue from heavy blood loss. Read more on the symptoms and causes of fibroids from the Mayo Clinic - https://www.mayoclinic.org/diseases-conditions/uterine-fibroids/symptoms-causes/syc-20354288#:~:text=Uterine%20fibroids%20often%20aren%27t,fatigue%20from%20heavy%20blood%20loss \n\nTeri: Thank you for the chat today. Come back anytime you have more questions.\n",
             (True, False, False) : "\nTeri: Based on your answers, here are a few resources that may be helpful: \n\nFibroids are tumors made of smooth muscle cells and fibrous connective tissue that develop in the uterus. It is estimated that 70 to 80 percent of women will develop fibroids in their lifetime — however, not everyone will develop symptoms or require treatment. Read more from UCLA Health - https://www.uclahealth.org/medical-services/fibroids/what-are-fibroids\n\nHysterectomy rates among Black women are more than double those of any other ethnic group.This statistic is rooted in the fact that some Black women are only offered this option. Read more on the experiences of Black women living fibroids at VeryWellHealth.com - https://www.verywellhealth.com/uterine-fibroids-coping-5188641\n\n \n\nTeri: Thank you for the chat today. Come back anytime you have more questions. \n",
             (False, False, False) : "\nTeri: Today I do not have any resources that can help you, but come back anytime you have more questions.\n",
             (False, True, False) : "\nTeri: Based on your answers, here are a few resources that may be helpful: \n\nUterine fibroids often aren't dangerous. But they can cause pain, and they may lead to complications. These include a drop in red blood cells called anemia. That condition can cause fatigue from heavy blood loss. Read more on the symptoms and causes of fibroids from the Mayo Clinic - https://www.mayoclinic.org/diseases-conditions/uterine-fibroids/symptoms-causes/syc-20354288#:~:text=Uterine%20fibroids%20often%20aren%27t,fatigue%20from%20heavy%20blood%20loss \n\nTeri: Thank you for the chat today. Come back anytime you have more questions.\n",
             (False, True, True) : "\nTeri: Based on your answers, here are a few resources that may be helpful: \n\nUterine fibroids often aren't dangerous. But they can cause pain, and they may lead to complications. These include a drop in red blood cells called anemia. That condition can cause fatigue from heavy blood loss. Read more on the symptoms and causes of fibroids from the Mayo Clinic - https://www.mayoclinic.org/diseases-conditions/uterine-fibroids/symptoms-causes/syc-20354288#:~:text=Uterine%20fibroids%20often%20aren%27t,fatigue%20from%20heavy%20blood%20loss \n\nMost women will experience no effects from fibroids during their pregnancy. However, a 2010 review suggests 10 to 30 percent  of women with fibroids develop complications during pregnancy. Read more on how fibroids affect pregnancy and fertility?- https://www.healthline.com/health/womens-health/fibroids-pregnancy \n\nTeri: Thank you for the chat today. Come back anytime you have more questions.\n",
             (True, False, True) : "\nTeri: Based on your answers, here are a few resources that may be helpful: \n\nFibroids are tumors made of smooth muscle cells and fibrous connective tissue that develop in the uterus. It is estimated that 70 to 80 percent of women will develop fibroids in their lifetime — however, not everyone will develop symptoms or require treatment. Read more from UCLA Health - https://www.uclahealth.org/medical-services/fibroids/what-are-fibroids \n\nMost women will experience no effects from fibroids during their pregnancy. However, a 2010 review suggests 10 to 30 percent  of women with fibroids develop complications during pregnancy. Read more on how fibroids affect pregnancy and fertility?- https://www.healthline.com/health/womens-health/fibroids-pregnancy \n\nTeri: Thank you for the chat today. Come back anytime you have more questions.\n"}

answers = []
questions = ["\nTeri: Would you like information on what fibroids are? Yes/No\n\nYou: ",
            "\nTeri: Would you like information on how fibroids may affect your physical health? Yes/No\n\nYou: ",
            "\nTeri: Would you like to know more about how fibroids may affect pregnancy and fertility? Yes/No\n\nYou: "
            ]

questions_ally_info = ["\nTeri: Would you like information on what fibroids are? Yes/No\n\nYou: ",
            "\nTeri: Would you like information on how fibroids may a person's physical health? Yes/No\n\nYou: ",
            "\nTeri: Would you like to know more about how fibroids may affect a person's pregnancy and fertility? Yes/No\n\nYou: "
            ]

def chatbot():

    print("Teri: Hello! I am Teri, your U2rUs chatbot assistant to help you address your needs and concerns around uterine care.\n")
    sys.stdout.flush()
    sleep(1.0)

    while True:

        response = input("Teri: Can I ask you a few questions so that I can better assist you? (Yes/No)\n\nYou: ").lower()



        if response in ['no', 'n', 'nah', 'naw']:
            print('Teri: Ok, have a great day!')
            break

        elif response in ['yes', 'y', 'yea']:


            # Ask for the user's name
            user_name = input("\nTeri: What is your name?\n\nYou: ").lower().capitalize()
            print(f'\nTeri: Nice to meet you, {user_name}. As a chatbot, I can help you: \n')
            sys.stdout.flush()
            sleep(1.0)
            print('1. Find more information about fibroids\n')

            #adding delay before printing next question
            sys.stdout.flush()
            sleep(1.0)
            print('2. Prepare for a medical visit\n')
            sys.stdout.flush()
            sleep(1.0)
            print('3. Learn more about care and support for yourself or someone living with fibroids.\n')
            sys.stdout.flush()
            sleep(1.0)

            while True:
                intent = input(f'Teri: How can I help you today, {user_name}? Please enter the number of one of the options you are interested in: 1, 2 or 3.\n\nYou: ')
                # conversation that will direct user to educational / material resources
                if intent == str(1):
                    while True:
                        role = input('\nTeri: Are you a carrier (someone who has a uterus) or are you an ally supporting a carrier in their health journey?\n\nYou:  ').lower()
                        carrier_pattern = r'\bc\w*r\b'
                        ally_pattern = r'\ba\w*y\b'
                        if bool(re.match(carrier_pattern, role))==True:
                            while True:
                                age = input('\nTeri: How old are you?\n\nYou: ')
                                if age.isdigit():
                                    age=int(age)
                                    family_history = input('\nTeri: Does your family have a history of uterine fibroids? (Yes/No)\n\nYou: ')

                                    for q in questions:
                                       answers.append(ask_question(q))


                                    print(responses[tuple(answers)])

                                    break


                                else:
                                    print("Please enter your age in numbers. i.e. 55, 23.")
                                    continue

                        elif bool(re.match(ally_pattern, role))==True:
                            for q in questions_ally_info:
                                answers.append(ask_question(q))
                            print(responses[tuple(answers)])

                        else:
                          print("Teri: Please enter 'carrier' or 'ally'. ")
                          continue
                        break



                # conversation that will direct user to medical intake questions
                elif intent == str(2):
                    # Preface questions
                    print('\nTeri: In the next few questions, I will ask you about your medical history. These questions are questions asked commonly asked during a doctor consultation. They allow you to let your doctor know your current and path health experiences, and helping the doctor better meet your needs.\n')
                    sys.stdout.flush()
                    sleep(2.0)
                    # Ask for the user's age
                    age = int(input("Teri: How old are you?\n\nYou: "))


                    questions_and_answers = {
                        "Name": user_name,
                        "Age": age,
                    }

                    pregnancy = input("\nTeri: Are you currently pregnant? (Yes/No)\n\nYou: ")
                    questions_and_answers["Pregnant"] = pregnancy
                    sys.stdout.flush()
                    sleep(0.5)
                    future = input("\nTeri: Are you planning on a future pregnancy? (Yes/No)\n\nYou: ")
                    questions_and_answers["Planning_Pregnancy"] = future
                    sys.stdout.flush()
                    sleep(0.5)
                    menopause = input("\nTeri: Are you currently in menopause? (Yes/No)\n\nYou: ")
                    questions_and_answers["Menopause"] = menopause
                    sys.stdout.flush()
                    sleep(0.5)
                    past_menopause = input("\nTeri: Have you already completed menopause? (Yes/No)\n\nYou: ")
                    questions_and_answers["Past_Menopause"] = past_menopause
                    sys.stdout.flush()
                    sleep(0.5)
                    family_history = input("\nTeri: Do you have a family history of fibroids? (Yes/No)\n\nYou: ")
                    questions_and_answers["Tamily_History"] = family_history

                    medications = input("\nTeri: What medications are you on? Please separate all medicines by comma. (Example: Eligard, Zoladex)\n\nYou: ")
                    questions_and_answers["Medications"] = medications

                    if ',' in medications:
                        # Parse medications
                        medications_list = medications.split(',')
                        for i, medication in enumerate(medications_list, start=1):
                          medication = medication.lower().capitalize().lstrip()
                          duration = input(f"\nTeri: How long have you been on '{medication}'?\n\nYou: ")
                          questions_and_answers[f"{medication} Duration"] = duration
                    else:
                        medications_list = medications.lower().capitalize().lstrip()
                        duration = input(f"\nTeri: How long have you been on '{medications_list}'?\n\nYou: ")
                        questions_and_answers[f"{medications_list} Duration"] = duration

                    symptoms = input("\nTeri: What symptoms or ailments have you been experiencing? Please separate all symptoms by comma. (Example: back pain, fever)\n\nYou: ")
                    questions_and_answers["Symptoms"] = symptoms

                    if ',' in symptoms:
                        # Parse symptoms
                        symptoms_list = symptoms.split(',')
                        for i, symptom in enumerate(symptoms_list, start=1):
                            symptom = symptom.lower().capitalize().lstrip()
                            duration = input(f"\nTeri: How long have you been experiencing '{symptom}'?\n\nYou: ")
                            questions_and_answers[f"{symptom} Duration"] = duration
                    else:
                        symptoms_list = symptoms.lower().capitalize().lstrip()
                        duration = input(f"\nTeri: How long have you been experiencing '{symptoms_list}'?\n\nYou: ")
                        questions_and_answers[f"{symptoms_list} Duration"] = duration


                    # Summarize the questions and answers
                    print("\nTeri: Here is a summary of our conversation. You can share this with your doctor at your next consultation:\n\n")
                    for question, answer in questions_and_answers.items():
                        print(f"- {question}: {answer}")
                    send = input('\nTeri: Would you like to send your data to a health care provider? (Yes/No)\n\nYou: ').lower().strip()
                    if send in ['y', 'yea', 'yes']:
                          email = input('\nTeri: Please provide the email of your health care provider so that a copy may be sent to them.\n\nYou: ')
                          print(f'\nTeri. Thank you! Your answers will be sent to {email}.\n')

                    else:
                        print('Teri: Ok, your answers will not be shared with a health care provider. Have a great day!')

                # conversation that will direct user to support resources
                elif intent == str(3):
                    while True:
                        role = input('\nTeri: Are you a carrier (someone who has a uterus) or are you an ally supporting a carrier in their health journey?\n\nYou:  ').lower()
                        carrier_pattern = r'\bc\w*r\b'
                        ally_pattern = r'\ba\w*y\b'
                        if bool(re.match(carrier_pattern, role))==True:
                            print('\nTeri: Fibroids can also affect your mental health. You’re likely to feel down, irritated, or grumpy. Read more at Heathline.com - https://www.healthline.com/health/womens-health/uterine-fibroids-talking-with-partner#mental-health\n\nHospitals and health clinics may offer support groups for women and families affected by fibroids. Find out more from the National Institutes of Health - https://www.nichd.nih.gov/health/topics/uterine/conditioninfo/treatments/support#:~:text=Many%20women%20find%20that%20joining,you%20to%20a%20support%20group.\n\n')


                        elif bool(re.match(ally_pattern, role))==True:
                            print('\nTeri: Fibroids can also affect your mental health. You’re likely to feel down, irritated, or grumpy. Read more at Heathline.com - https://www.healthline.com/health/womens-health/uterine-fibroids-talking-with-partner#mental-health\n\n')

                        else:
                          print("Teri: Please enter 'carrier' or 'ally'. ")
                          continue
                        break



                else:
                    print("\nTeri: I'm sorry I do not understand. Please enter a valid option: 1, 2, or 3\n\n" )
                    continue
                    sys.stdout.flush()
                    sleep(0.0)
                break

        else:
            print("\nTeri: I'm sorry. I do not understand. Please enter 'Yes' or 'No'. \n\n")
            continue

        break


    # End
    print('Teri: Thank you for your time. Goodbye!')


if __name__ == "__main__":
    chatbot()



